// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/proto/snake.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_pkg_proto_snake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_snake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_pkg_proto_snake_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type FoodInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Pos              *Point                 `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	FoodType         int32                  `protobuf:"varint,2,opt,name=foodType,proto3" json:"foodType,omitempty"`
	RemainingSeconds int32                  `protobuf:"varint,3,opt,name=remainingSeconds,proto3" json:"remainingSeconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FoodInfo) Reset() {
	*x = FoodInfo{}
	mi := &file_pkg_proto_snake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodInfo) ProtoMessage() {}

func (x *FoodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_snake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodInfo.ProtoReflect.Descriptor instead.
func (*FoodInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_snake_proto_rawDescGZIP(), []int{1}
}

func (x *FoodInfo) GetPos() *Point {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *FoodInfo) GetFoodType() int32 {
	if x != nil {
		return x.FoodType
	}
	return 0
}

func (x *FoodInfo) GetRemainingSeconds() int32 {
	if x != nil {
		return x.RemainingSeconds
	}
	return 0
}

type Obstacle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Duration      float64                `protobuf:"fixed64,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Obstacle) Reset() {
	*x = Obstacle{}
	mi := &file_pkg_proto_snake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Obstacle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Obstacle) ProtoMessage() {}

func (x *Obstacle) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_snake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Obstacle.ProtoReflect.Descriptor instead.
func (*Obstacle) Descriptor() ([]byte, []int) {
	return file_pkg_proto_snake_proto_rawDescGZIP(), []int{2}
}

func (x *Obstacle) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *Obstacle) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Fireball struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *Point                 `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Dir           *Point                 `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fireball) Reset() {
	*x = Fireball{}
	mi := &file_pkg_proto_snake_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fireball) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fireball) ProtoMessage() {}

func (x *Fireball) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_snake_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fireball.ProtoReflect.Descriptor instead.
func (*Fireball) Descriptor() ([]byte, []int) {
	return file_pkg_proto_snake_proto_rawDescGZIP(), []int{3}
}

func (x *Fireball) GetPos() *Point {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Fireball) GetDir() *Point {
	if x != nil {
		return x.Dir
	}
	return nil
}

func (x *Fireball) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type ScoreEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *Point                 `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreEvent) Reset() {
	*x = ScoreEvent{}
	mi := &file_pkg_proto_snake_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreEvent) ProtoMessage() {}

func (x *ScoreEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_snake_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreEvent.ProtoReflect.Descriptor instead.
func (*ScoreEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_snake_proto_rawDescGZIP(), []int{4}
}

func (x *ScoreEvent) GetPos() *Point {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *ScoreEvent) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ScoreEvent) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // ISO string
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Mode          string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_pkg_proto_snake_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_snake_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_pkg_proto_snake_proto_rawDescGZIP(), []int{5}
}

func (x *LeaderboardEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardEntry) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *LeaderboardEntry) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *LeaderboardEntry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type WinRateEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	WinRate       float64                `protobuf:"fixed64,2,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	TotalWins     int32                  `protobuf:"varint,3,opt,name=total_wins,json=totalWins,proto3" json:"total_wins,omitempty"`
	TotalGames    int32                  `protobuf:"varint,4,opt,name=total_games,json=totalGames,proto3" json:"total_games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WinRateEntry) Reset() {
	*x = WinRateEntry{}
	mi := &file_pkg_proto_snake_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinRateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinRateEntry) ProtoMessage() {}

func (x *WinRateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_snake_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinRateEntry.ProtoReflect.Descriptor instead.
func (*WinRateEntry) Descriptor() ([]byte, []int) {
	return file_pkg_proto_snake_proto_rawDescGZIP(), []int{6}
}

func (x *WinRateEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WinRateEntry) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *WinRateEntry) GetTotalWins() int32 {
	if x != nil {
		return x.TotalWins
	}
	return 0
}

func (x *WinRateEntry) GetTotalGames() int32 {
	if x != nil {
		return x.TotalGames
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	BestScore     int32                  `protobuf:"varint,2,opt,name=best_score,json=bestScore,proto3" json:"best_score,omitempty"`
	TotalGames    int32                  `protobuf:"varint,3,opt,name=total_games,json=totalGames,proto3" json:"total_games,omitempty"`
	TotalWins     int32                  `protobuf:"varint,4,opt,name=total_wins,json=totalWins,proto3" json:"total_wins,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_pkg_proto_snake_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_snake_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pkg_proto_snake_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetBestScore() int32 {
	if x != nil {
		return x.BestScore
	}
	return 0
}

func (x *User) GetTotalGames() int32 {
	if x != nil {
		return x.TotalGames
	}
	return 0
}

func (x *User) GetTotalWins() int32 {
	if x != nil {
		return x.TotalWins
	}
	return 0
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GameStateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snake         []*Point               `protobuf:"bytes,1,rep,name=snake,proto3" json:"snake,omitempty"`
	Foods         []*FoodInfo            `protobuf:"bytes,2,rep,name=foods,proto3" json:"foods,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	FoodEaten     int32                  `protobuf:"varint,4,opt,name=foodEaten,proto3" json:"foodEaten,omitempty"`
	EatingSpeed   float64                `protobuf:"fixed64,5,opt,name=eatingSpeed,proto3" json:"eatingSpeed,omitempty"`
	Started       bool                   `protobuf:"varint,6,opt,name=started,proto3" json:"started,omitempty"`
	GameOver      bool                   `protobuf:"varint,7,opt,name=gameOver,proto3" json:"gameOver,omitempty"`
	Paused        bool                   `protobuf:"varint,8,opt,name=paused,proto3" json:"paused,omitempty"`
	Boosting      bool                   `protobuf:"varint,9,opt,name=boosting,proto3" json:"boosting,omitempty"`
	AutoPlay      bool                   `protobuf:"varint,10,opt,name=autoPlay,proto3" json:"autoPlay,omitempty"`
	Difficulty    string                 `protobuf:"bytes,11,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Message       string                 `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty"`
	MessageType   string                 `protobuf:"bytes,13,opt,name=messageType,proto3" json:"messageType,omitempty"`
	CrashPoint    *Point                 `protobuf:"bytes,14,opt,name=crashPoint,proto3" json:"crashPoint,omitempty"`
	Obstacles     []*Obstacle            `protobuf:"bytes,15,rep,name=obstacles,proto3" json:"obstacles,omitempty"`
	Fireballs     []*Fireball            `protobuf:"bytes,16,rep,name=fireballs,proto3" json:"fireballs,omitempty"`
	HitPoints     []*Point               `protobuf:"bytes,17,rep,name=hitPoints,proto3" json:"hitPoints,omitempty"`
	AiSnake       []*Point               `protobuf:"bytes,18,rep,name=aiSnake,proto3" json:"aiSnake,omitempty"`
	AiScore       int32                  `protobuf:"varint,19,opt,name=aiScore,proto3" json:"aiScore,omitempty"`
	TimeRemaining int32                  `protobuf:"varint,20,opt,name=timeRemaining,proto3" json:"timeRemaining,omitempty"`
	Winner        string                 `protobuf:"bytes,21,opt,name=winner,proto3" json:"winner,omitempty"`
	AiStunned     bool                   `protobuf:"varint,22,opt,name=aiStunned,proto3" json:"aiStunned,omitempty"`
	PlayerStunned bool                   `protobuf:"varint,23,opt,name=playerStunned,proto3" json:"playerStunned,omitempty"`
	Mode          string                 `protobuf:"bytes,24,opt,name=mode,proto3" json:"mode,omitempty"`
	ScoreEvents   []*ScoreEvent          `protobuf:"bytes,25,rep,name=scoreEvents,proto3" json:"scoreEvents,omitempty"`
	Berserker     bool                   `protobuf:"varint,26,opt,name=berserker,proto3" json:"berserker,omitempty"`
	IsPVP         bool                   `protobuf:"varint,27,opt,name=isPVP,proto3" json:"isPVP,omitempty"`
	P1Name        string                 `protobuf:"bytes,28,opt,name=p1Name,proto3" json:"p1Name,omitempty"`
	P2Name        string                 `protobuf:"bytes,29,opt,name=p2Name,proto3" json:"p2Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateSnapshot) Reset() {
	*x = GameStateSnapshot{}
	mi := &file_pkg_proto_snake_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateSnapshot) ProtoMessage() {}

func (x *GameStateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_snake_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateSnapshot.ProtoReflect.Descriptor instead.
func (*GameStateSnapshot) Descriptor() ([]byte, []int) {
	return file_pkg_proto_snake_proto_rawDescGZIP(), []int{8}
}

func (x *GameStateSnapshot) GetSnake() []*Point {
	if x != nil {
		return x.Snake
	}
	return nil
}

func (x *GameStateSnapshot) GetFoods() []*FoodInfo {
	if x != nil {
		return x.Foods
	}
	return nil
}

func (x *GameStateSnapshot) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GameStateSnapshot) GetFoodEaten() int32 {
	if x != nil {
		return x.FoodEaten
	}
	return 0
}

func (x *GameStateSnapshot) GetEatingSpeed() float64 {
	if x != nil {
		return x.EatingSpeed
	}
	return 0
}

func (x *GameStateSnapshot) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *GameStateSnapshot) GetGameOver() bool {
	if x != nil {
		return x.GameOver
	}
	return false
}

func (x *GameStateSnapshot) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *GameStateSnapshot) GetBoosting() bool {
	if x != nil {
		return x.Boosting
	}
	return false
}

func (x *GameStateSnapshot) GetAutoPlay() bool {
	if x != nil {
		return x.AutoPlay
	}
	return false
}

func (x *GameStateSnapshot) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *GameStateSnapshot) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GameStateSnapshot) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *GameStateSnapshot) GetCrashPoint() *Point {
	if x != nil {
		return x.CrashPoint
	}
	return nil
}

func (x *GameStateSnapshot) GetObstacles() []*Obstacle {
	if x != nil {
		return x.Obstacles
	}
	return nil
}

func (x *GameStateSnapshot) GetFireballs() []*Fireball {
	if x != nil {
		return x.Fireballs
	}
	return nil
}

func (x *GameStateSnapshot) GetHitPoints() []*Point {
	if x != nil {
		return x.HitPoints
	}
	return nil
}

func (x *GameStateSnapshot) GetAiSnake() []*Point {
	if x != nil {
		return x.AiSnake
	}
	return nil
}

func (x *GameStateSnapshot) GetAiScore() int32 {
	if x != nil {
		return x.AiScore
	}
	return 0
}

func (x *GameStateSnapshot) GetTimeRemaining() int32 {
	if x != nil {
		return x.TimeRemaining
	}
	return 0
}

func (x *GameStateSnapshot) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *GameStateSnapshot) GetAiStunned() bool {
	if x != nil {
		return x.AiStunned
	}
	return false
}

func (x *GameStateSnapshot) GetPlayerStunned() bool {
	if x != nil {
		return x.PlayerStunned
	}
	return false
}

func (x *GameStateSnapshot) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GameStateSnapshot) GetScoreEvents() []*ScoreEvent {
	if x != nil {
		return x.ScoreEvents
	}
	return nil
}

func (x *GameStateSnapshot) GetBerserker() bool {
	if x != nil {
		return x.Berserker
	}
	return false
}

func (x *GameStateSnapshot) GetIsPVP() bool {
	if x != nil {
		return x.IsPVP
	}
	return false
}

func (x *GameStateSnapshot) GetP1Name() string {
	if x != nil {
		return x.P1Name
	}
	return ""
}

func (x *GameStateSnapshot) GetP2Name() string {
	if x != nil {
		return x.P2Name
	}
	return ""
}

type GameConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Width            int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height           int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	GameDuration     int32                  `protobuf:"varint,3,opt,name=gameDuration,proto3" json:"gameDuration,omitempty"`
	FireballCooldown int32                  `protobuf:"varint,4,opt,name=fireballCooldown,proto3" json:"fireballCooldown,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GameConfig) Reset() {
	*x = GameConfig{}
	mi := &file_pkg_proto_snake_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameConfig) ProtoMessage() {}

func (x *GameConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_snake_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameConfig.ProtoReflect.Descriptor instead.
func (*GameConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_snake_proto_rawDescGZIP(), []int{9}
}

func (x *GameConfig) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GameConfig) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GameConfig) GetGameDuration() int32 {
	if x != nil {
		return x.GameDuration
	}
	return 0
}

func (x *GameConfig) GetFireballCooldown() int32 {
	if x != nil {
		return x.FireballCooldown
	}
	return 0
}

type ServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Config        *GameConfig            `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	State         *GameStateSnapshot     `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Leaderboard   []*LeaderboardEntry    `protobuf:"bytes,4,rep,name=leaderboard,proto3" json:"leaderboard,omitempty"`
	WinRates      []*WinRateEntry        `protobuf:"bytes,5,rep,name=win_rates,json=winRates,proto3" json:"win_rates,omitempty"`
	User          *User                  `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	Success       string                 `protobuf:"bytes,8,opt,name=success,proto3" json:"success,omitempty"`
	SessionCount  int32                  `protobuf:"varint,9,opt,name=sessionCount,proto3" json:"sessionCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_pkg_proto_snake_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_snake_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_snake_proto_rawDescGZIP(), []int{10}
}

func (x *ServerMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServerMessage) GetConfig() *GameConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ServerMessage) GetState() *GameStateSnapshot {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ServerMessage) GetLeaderboard() []*LeaderboardEntry {
	if x != nil {
		return x.Leaderboard
	}
	return nil
}

func (x *ServerMessage) GetWinRates() []*WinRateEntry {
	if x != nil {
		return x.WinRates
	}
	return nil
}

func (x *ServerMessage) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ServerMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ServerMessage) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

func (x *ServerMessage) GetSessionCount() int32 {
	if x != nil {
		return x.SessionCount
	}
	return 0
}

type ClientMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Mode          string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	Feedback      string                 `protobuf:"bytes,6,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_pkg_proto_snake_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_snake_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_snake_proto_rawDescGZIP(), []int{11}
}

func (x *ClientMessage) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ClientMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ClientMessage) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ClientMessage) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

var File_pkg_proto_snake_proto protoreflect.FileDescriptor

const file_pkg_proto_snake_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/snake.proto\x12\x05snake\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"r\n" +
	"\bFoodInfo\x12\x1e\n" +
	"\x03pos\x18\x01 \x01(\v2\f.snake.PointR\x03pos\x12\x1a\n" +
	"\bfoodType\x18\x02 \x01(\x05R\bfoodType\x12*\n" +
	"\x10remainingSeconds\x18\x03 \x01(\x05R\x10remainingSeconds\"L\n" +
	"\bObstacle\x12$\n" +
	"\x06points\x18\x01 \x03(\v2\f.snake.PointR\x06points\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x01R\bduration\"`\n" +
	"\bFireball\x12\x1e\n" +
	"\x03pos\x18\x01 \x01(\v2\f.snake.PointR\x03pos\x12\x1e\n" +
	"\x03dir\x18\x02 \x01(\v2\f.snake.PointR\x03dir\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\"Z\n" +
	"\n" +
	"ScoreEvent\x12\x1e\n" +
	"\x03pos\x18\x01 \x01(\v2\f.snake.PointR\x03pos\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"\x84\x01\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\"}\n" +
	"\fWinRateEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bwin_rate\x18\x02 \x01(\x01R\awinRate\x12\x1d\n" +
	"\n" +
	"total_wins\x18\x03 \x01(\x05R\ttotalWins\x12\x1f\n" +
	"\vtotal_games\x18\x04 \x01(\x05R\n" +
	"totalGames\"\xa0\x01\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"best_score\x18\x02 \x01(\x05R\tbestScore\x12\x1f\n" +
	"\vtotal_games\x18\x03 \x01(\x05R\n" +
	"totalGames\x12\x1d\n" +
	"\n" +
	"total_wins\x18\x04 \x01(\x05R\ttotalWins\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xbf\a\n" +
	"\x11GameStateSnapshot\x12\"\n" +
	"\x05snake\x18\x01 \x03(\v2\f.snake.PointR\x05snake\x12%\n" +
	"\x05foods\x18\x02 \x03(\v2\x0f.snake.FoodInfoR\x05foods\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x1c\n" +
	"\tfoodEaten\x18\x04 \x01(\x05R\tfoodEaten\x12 \n" +
	"\veatingSpeed\x18\x05 \x01(\x01R\veatingSpeed\x12\x18\n" +
	"\astarted\x18\x06 \x01(\bR\astarted\x12\x1a\n" +
	"\bgameOver\x18\a \x01(\bR\bgameOver\x12\x16\n" +
	"\x06paused\x18\b \x01(\bR\x06paused\x12\x1a\n" +
	"\bboosting\x18\t \x01(\bR\bboosting\x12\x1a\n" +
	"\bautoPlay\x18\n" +
	" \x01(\bR\bautoPlay\x12\x1e\n" +
	"\n" +
	"difficulty\x18\v \x01(\tR\n" +
	"difficulty\x12\x18\n" +
	"\amessage\x18\f \x01(\tR\amessage\x12 \n" +
	"\vmessageType\x18\r \x01(\tR\vmessageType\x12,\n" +
	"\n" +
	"crashPoint\x18\x0e \x01(\v2\f.snake.PointR\n" +
	"crashPoint\x12-\n" +
	"\tobstacles\x18\x0f \x03(\v2\x0f.snake.ObstacleR\tobstacles\x12-\n" +
	"\tfireballs\x18\x10 \x03(\v2\x0f.snake.FireballR\tfireballs\x12*\n" +
	"\thitPoints\x18\x11 \x03(\v2\f.snake.PointR\thitPoints\x12&\n" +
	"\aaiSnake\x18\x12 \x03(\v2\f.snake.PointR\aaiSnake\x12\x18\n" +
	"\aaiScore\x18\x13 \x01(\x05R\aaiScore\x12$\n" +
	"\rtimeRemaining\x18\x14 \x01(\x05R\rtimeRemaining\x12\x16\n" +
	"\x06winner\x18\x15 \x01(\tR\x06winner\x12\x1c\n" +
	"\taiStunned\x18\x16 \x01(\bR\taiStunned\x12$\n" +
	"\rplayerStunned\x18\x17 \x01(\bR\rplayerStunned\x12\x12\n" +
	"\x04mode\x18\x18 \x01(\tR\x04mode\x123\n" +
	"\vscoreEvents\x18\x19 \x03(\v2\x11.snake.ScoreEventR\vscoreEvents\x12\x1c\n" +
	"\tberserker\x18\x1a \x01(\bR\tberserker\x12\x14\n" +
	"\x05isPVP\x18\x1b \x01(\bR\x05isPVP\x12\x16\n" +
	"\x06p1Name\x18\x1c \x01(\tR\x06p1Name\x12\x16\n" +
	"\x06p2Name\x18\x1d \x01(\tR\x06p2Name\"\x8a\x01\n" +
	"\n" +
	"GameConfig\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\"\n" +
	"\fgameDuration\x18\x03 \x01(\x05R\fgameDuration\x12*\n" +
	"\x10fireballCooldown\x18\x04 \x01(\x05R\x10fireballCooldown\"\xe0\x02\n" +
	"\rServerMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12)\n" +
	"\x06config\x18\x02 \x01(\v2\x11.snake.GameConfigR\x06config\x12.\n" +
	"\x05state\x18\x03 \x01(\v2\x18.snake.GameStateSnapshotR\x05state\x129\n" +
	"\vleaderboard\x18\x04 \x03(\v2\x17.snake.LeaderboardEntryR\vleaderboard\x120\n" +
	"\twin_rates\x18\x05 \x03(\v2\x13.snake.WinRateEntryR\bwinRates\x12\x1f\n" +
	"\x04user\x18\x06 \x01(\v2\v.snake.UserR\x04user\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\b \x01(\tR\asuccess\x12\"\n" +
	"\fsessionCount\x18\t \x01(\x05R\fsessionCount\"\xa3\x01\n" +
	"\rClientMessage\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\x12\x1a\n" +
	"\bfeedback\x18\x06 \x01(\tR\bfeedbackB*Z(github.com/trytobebee/snake_go/pkg/protob\x06proto3"

var (
	file_pkg_proto_snake_proto_rawDescOnce sync.Once
	file_pkg_proto_snake_proto_rawDescData []byte
)

func file_pkg_proto_snake_proto_rawDescGZIP() []byte {
	file_pkg_proto_snake_proto_rawDescOnce.Do(func() {
		file_pkg_proto_snake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_snake_proto_rawDesc), len(file_pkg_proto_snake_proto_rawDesc)))
	})
	return file_pkg_proto_snake_proto_rawDescData
}

var file_pkg_proto_snake_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_proto_snake_proto_goTypes = []any{
	(*Point)(nil),             // 0: snake.Point
	(*FoodInfo)(nil),          // 1: snake.FoodInfo
	(*Obstacle)(nil),          // 2: snake.Obstacle
	(*Fireball)(nil),          // 3: snake.Fireball
	(*ScoreEvent)(nil),        // 4: snake.ScoreEvent
	(*LeaderboardEntry)(nil),  // 5: snake.LeaderboardEntry
	(*WinRateEntry)(nil),      // 6: snake.WinRateEntry
	(*User)(nil),              // 7: snake.User
	(*GameStateSnapshot)(nil), // 8: snake.GameStateSnapshot
	(*GameConfig)(nil),        // 9: snake.GameConfig
	(*ServerMessage)(nil),     // 10: snake.ServerMessage
	(*ClientMessage)(nil),     // 11: snake.ClientMessage
}
var file_pkg_proto_snake_proto_depIdxs = []int32{
	0,  // 0: snake.FoodInfo.pos:type_name -> snake.Point
	0,  // 1: snake.Obstacle.points:type_name -> snake.Point
	0,  // 2: snake.Fireball.pos:type_name -> snake.Point
	0,  // 3: snake.Fireball.dir:type_name -> snake.Point
	0,  // 4: snake.ScoreEvent.pos:type_name -> snake.Point
	0,  // 5: snake.GameStateSnapshot.snake:type_name -> snake.Point
	1,  // 6: snake.GameStateSnapshot.foods:type_name -> snake.FoodInfo
	0,  // 7: snake.GameStateSnapshot.crashPoint:type_name -> snake.Point
	2,  // 8: snake.GameStateSnapshot.obstacles:type_name -> snake.Obstacle
	3,  // 9: snake.GameStateSnapshot.fireballs:type_name -> snake.Fireball
	0,  // 10: snake.GameStateSnapshot.hitPoints:type_name -> snake.Point
	0,  // 11: snake.GameStateSnapshot.aiSnake:type_name -> snake.Point
	4,  // 12: snake.GameStateSnapshot.scoreEvents:type_name -> snake.ScoreEvent
	9,  // 13: snake.ServerMessage.config:type_name -> snake.GameConfig
	8,  // 14: snake.ServerMessage.state:type_name -> snake.GameStateSnapshot
	5,  // 15: snake.ServerMessage.leaderboard:type_name -> snake.LeaderboardEntry
	6,  // 16: snake.ServerMessage.win_rates:type_name -> snake.WinRateEntry
	7,  // 17: snake.ServerMessage.user:type_name -> snake.User
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pkg_proto_snake_proto_init() }
func file_pkg_proto_snake_proto_init() {
	if File_pkg_proto_snake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_snake_proto_rawDesc), len(file_pkg_proto_snake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_snake_proto_goTypes,
		DependencyIndexes: file_pkg_proto_snake_proto_depIdxs,
		MessageInfos:      file_pkg_proto_snake_proto_msgTypes,
	}.Build()
	File_pkg_proto_snake_proto = out.File
	file_pkg_proto_snake_proto_goTypes = nil
	file_pkg_proto_snake_proto_depIdxs = nil
}
